# Generated by Django 5.2.5 on 2025-08-12 17:07

import django.db.models.deletion
import referrals.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Referral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(default=referrals.models.generate_reference, editable=False, max_length=20, unique=True)),
                ('student_name', models.CharField(max_length=120)),
                ('grade', models.CharField(choices=[('1', 'الصف 1'), ('2', 'الصف 2'), ('3', 'الصف 3'), ('4', 'الصف 4'), ('5', 'الصف 5'), ('6', 'الصف 6'), ('7', 'الصف 7'), ('8', 'الصف 8'), ('9', 'الصف 9'), ('10', 'الصف 10'), ('11', 'الصف 11'), ('12', 'الصف 12')], max_length=2)),
                ('referral_type', models.CharField(choices=[('behavior', 'سلوكي'), ('academic', 'تحصيلي'), ('health', 'صحي'), ('other', 'أخرى')], max_length=20)),
                ('details', models.TextField()),
                ('status', models.CharField(choices=[('NEW', 'جديدة'), ('UNDER_REVIEW', 'قيد المراجعة'), ('SENT_TO_DEPUTY', 'محالة لوكيل'), ('CLOSED', 'مغلقة')], default='NEW', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assignee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_referrals', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_referrals', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=referrals.models.referral_upload_path)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('referral', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='referrals.referral')),
            ],
        ),
    ]
