# Generated by Django 5.2.5 on 2025-08-14 14:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referrals', '0002_action_actionattachment'),
    ]

    operations = [
        migrations.CreateModel(
            name='CounselorIntake',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('father_alive', models.BooleanField(default=True, verbose_name='هل الأب على قيد الحياة؟')),
                ('mother_alive', models.BooleanField(default=True, verbose_name='هل الأم على قيد الحياة؟')),
                ('parents_status', models.CharField(choices=[('مستقران', 'مستقران'), ('منفصلان', 'منفصلان')], default='مستقران', max_length=20, verbose_name='الحالة الاجتماعية للوالدين')),
                ('siblings_count', models.PositiveIntegerField(default=0, verbose_name='عدد الإخوة والأخوات')),
                ('child_order', models.CharField(blank=True, max_length=50, verbose_name='ترتيب الطالب بين إخوته')),
                ('father_edu', models.CharField(choices=[('أمي', 'أمي'), ('يقرأ ويكتب', 'يقرأ ويكتب'), ('الابتدائية', 'الابتدائية'), ('المتوسطة', 'المتوسطة'), ('الثانوية', 'الثانوية'), ('بكالوريوس', 'بكالوريوس'), ('ماجستير', 'ماجستير'), ('دكتوراه', 'دكتوراه')], default='الثانوية', max_length=20, verbose_name='المستوى التعليمي للأب')),
                ('mother_edu', models.CharField(choices=[('أمي', 'أمي'), ('يقرأ ويكتب', 'يقرأ ويكتب'), ('الابتدائية', 'الابتدائية'), ('المتوسطة', 'المتوسطة'), ('الثانوية', 'الثانوية'), ('بكالوريوس', 'بكالوريوس'), ('ماجستير', 'ماجستير'), ('دكتوراه', 'دكتوراه')], default='الثانوية', max_length=20, verbose_name='المستوى التعليمي للأم')),
                ('father_job', models.CharField(blank=True, max_length=120, verbose_name='مهنة الأب')),
                ('mother_job', models.CharField(blank=True, max_length=120, verbose_name='مهنة الأم')),
                ('family_income', models.CharField(choices=[('أقل من 3000', 'أقل من (٣٠٠٠) ريال'), ('3000-6000', 'من (٣٠٠٠) إلى (٦٠٠٠) ريال'), ('6000-10000', 'من (٦٠٠٠) إلى (١٠٠٠٠) ريال'), ('أكثر من 10000', 'أكثر من (١٠٠٠٠) ريال')], default='3000-6000', max_length=20, verbose_name='دخل الأسرة')),
                ('has_insurance', models.BooleanField(default=False, verbose_name='هل يتم صرف ضمان اجتماعي لكم؟')),
                ('housing_type', models.CharField(choices=[('شقة', 'شقة'), ('بيت شعبي', 'بيت شعبي'), ('دور', 'دور')], default='شقة', max_length=20, verbose_name='نوع السكن')),
                ('housing_ownership', models.CharField(choices=[('ملك', 'ملك'), ('إيجار', 'إيجار')], default='إيجار', max_length=10, verbose_name='ملكية السكن')),
                ('receives_aid', models.BooleanField(default=False, verbose_name='هل تحصل على كرت مازيد بسهولة؟')),
                ('monthly_aid_amount', models.CharField(blank=True, max_length=50, verbose_name='قيمة المساعدة إن وُجدت')),
                ('health_asthma', models.BooleanField(default=False, verbose_name='ربو شعبي')),
                ('health_diabetes', models.BooleanField(default=False, verbose_name='سكر الدم')),
                ('health_epilepsy', models.BooleanField(default=False, verbose_name='تشنجات/صرع')),
                ('health_hearing', models.BooleanField(default=False, verbose_name='ضعف السمع')),
                ('health_heart', models.BooleanField(default=False, verbose_name='أمراض القلب')),
                ('health_bp', models.BooleanField(default=False, verbose_name='ضغط الدم')),
                ('health_kidney', models.BooleanField(default=False, verbose_name='التهاب الكلى')),
                ('health_sleep', models.BooleanField(default=False, verbose_name='النوم الكثير')),
                ('health_vision', models.BooleanField(default=False, verbose_name='ضعف البصر')),
                ('health_other', models.CharField(blank=True, max_length=200, verbose_name='أمراض أخرى تُذكر')),
                ('father_military', models.BooleanField(default=False, verbose_name='هل حالة عمل الأب في السلك العسكري؟')),
                ('at_south_border', models.BooleanField(default=False, verbose_name='هل الأب مرابط بالحد الجنوبي؟')),
                ('injured_south', models.BooleanField(default=False, verbose_name='هل أُصيب الأب في الحد الجنوبي؟')),
                ('father_martyr', models.BooleanField(default=False, verbose_name='هل الأب شهيد في الحد الجنوبي؟')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('referral', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='counselor_intake', to='referrals.referral')),
            ],
            options={
                'verbose_name': 'نموذج الموجّه الطلابي',
                'verbose_name_plural': 'نماذج الموجّه الطلابي',
            },
        ),
    ]
