# Generated by Django 5.2.5 on 2025-08-14 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referrals', '0003_counselorintake'),
    ]

    operations = [
        migrations.AddField(
            model_name='referral',
            name='student_key',
            field=models.CharField(blank=True, db_index=True, max_length=180, verbose_name='معرّف الطالب'),
        ),
        migrations.DeleteModel(
            name='CounselorIntake',
        ),
    ]
