# Generated by Django 5.2.5 on 2025-08-14 20:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('referrals', '0005_remove_referral_student_key_counselorintake'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CounselorIntake',
        ),
    ]
