# Generated by Django 5.2.5 on 2025-08-15 17:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referrals', '0006_delete_counselorintake'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='referral',
            name='student_key',
            field=models.CharField(blank=True, db_index=True, max_length=180, verbose_name='معرّف الطالب'),
        ),
        migrations.CreateModel(
            name='CounselorIntake',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('counselor_name', models.CharField(max_length=150, verbose_name='اسم الموجّه')),
                ('student_behavior', models.TextField(verbose_name='وصف السلوك/المشكلة')),
                ('previous_interventions', models.TextField(blank=True, verbose_name='إجراءات سابقة (إن وُجدت)')),
                ('recommendations', models.TextField(blank=True, verbose_name='التوصيات')),
                ('follow_up_date', models.DateField(blank=True, null=True, verbose_name='تاريخ المتابعة')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='أُنشئ في')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='عُدّل في')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_counselor_intakes', to=settings.AUTH_USER_MODEL, verbose_name='أنشئ بواسطة')),
                ('referral', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='counselor_intake', to='referrals.referral', verbose_name='الإحالة')),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='updated_counselor_intakes', to=settings.AUTH_USER_MODEL, verbose_name='آخر تعديل بواسطة')),
            ],
            options={
                'verbose_name': 'نموذج بيانات الموجّه',
                'verbose_name_plural': 'نماذج بيانات الموجّه',
                'ordering': ('-created_at',),
            },
        ),
    ]
