# Generated by Django 5.2.5 on 2025-08-15 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referrals', '0007_referral_student_key_counselorintake'),
    ]

    operations = [
        migrations.AddField(
            model_name='counselorintake',
            name='birth_order',
            field=models.CharField(blank=True, max_length=50, verbose_name='ترتيب الطالب بين إخوته وأخواته'),
        ),
        migrations.AddField(
            model_name='counselorintake',
            name='cond_allergy',
            field=models.BooleanField(default=False, verbose_name='حساسية موسمية'),
        ),
        migrations.AddField(
            model_name='counselorintake',
            name='cond_anemia',
            field=models.BooleanField(default=False, verbose_name='فقر الدم'),
        ),
        migrations.AddField(
            model_name='counselorintake',
            name='cond_asthma',
            field=models.BooleanField(default=False, verbose_name='ربو شعبي'),
        ),
        migrations.AddField(
            model_name='counselorintake',
            name='cond_diabetes',
            field=models.BooleanField(default=False, verbose_name='سكر الدم'),
        ),
        migrations.AddField(
            model_name='counselorintake',
            name='cond_disability',
            field=models.BooleanField(default=False, verbose_name='إعاقة أحد الأعضاء'),
        ),
        migrations.AddField(
            model_name='counselorintake',
            name='cond_hearing',
            field=models.BooleanField(default=False, verbose_name='ضعف السمع'),
        ),
        migrations.AddField(
            model_name='counselorintake',
            name='cond_rheumatism',
            field=models.BooleanField(default=False, verbose_name='روماتيزم'),
        ),
        migrations.AddField(
            model_name='counselorintake',
            name='cond_seizures',
            field=models.BooleanField(default=False, verbose_name='تشنجات/صرع'),
        ),
        migrations.AddField(
            model_name='counselorintake',
            name='cond_tonsils',
            field=models.BooleanField(default=False, verbose_name='التهاب اللوزتين'),
        ),
        migrations.AddField(
            model_name='counselorintake',
            name='disease_heart',
            field=models.BooleanField(default=False, verbose_name='أمراض القلب'),
        ),
        migrations.AddField(
            model_name='counselorintake',
            name='disease_kidney',
            field=models.BooleanField(default=False, verbose_name='الفشل الكلوي'),
        ),
        migrations.AddField(
            model_name='counselorintake',
            name='disease_other',
            field=models.CharField(blank=True, max_length=200, verbose_name='أمراض أخرى تُذكر'),
        ),
        migrations.AddField(
            model_name='counselorintake',
            name='disease_pressure',
            field=models.BooleanField(default=False, verbose_name='ضغط الدم'),
        ),
        migrations.AddField(
            model_name='counselorintake',
            name='disease_sleep',
            field=models.BooleanField(default=False, verbose_name='النوم المرضي'),
        ),
        migrations.AddField(
            model_name='counselorintake',
            name='disease_vision',
            field=models.BooleanField(default=False, verbose_name='ضعف البصر'),
        ),
        migrations.AddField(
            model_name='counselorintake',
            name='family_income',
            field=models.CharField(blank=True, choices=[('lt5', 'أقل من (٥,٠٠٠) ريال'), ('5to10', 'من (٥,٠٠٠) إلى (١٠,٠٠٠) ريال'), ('10to20', 'من (١٠,٠٠٠) إلى (٢٠,٠٠٠) ريال'), ('gt20', 'أكثر من (٢٠,٠٠٠) ريال')], max_length=10, verbose_name='دخل الأسرة'),
        ),
        migrations.AddField(
            model_name='counselorintake',
            name='father_alive',
            field=models.BooleanField(blank=True, null=True, verbose_name='هل الأب على قيد الحياة؟'),
        ),
        migrations.AddField(
            model_name='counselorintake',
            name='father_education',
            field=models.CharField(blank=True, choices=[('illiteracy', 'يقرأ ويكتب'), ('primary', 'الابتدائية'), ('middle', 'المتوسطة'), ('high', 'الثانوية'), ('bachelor', 'بكالوريوس'), ('master', 'ماجستير'), ('phd', 'دكتوراه')], max_length=20, verbose_name='المستوى التعليمي للأب'),
        ),
        migrations.AddField(
            model_name='counselorintake',
            name='father_in_military',
            field=models.BooleanField(blank=True, null=True, verbose_name='هل حالة عمل الأب في السلك العسكري؟'),
        ),
        migrations.AddField(
            model_name='counselorintake',
            name='father_is_martyr_south',
            field=models.BooleanField(blank=True, null=True, verbose_name='هل هو شهيد/في الحد الجنوبي؟'),
        ),
        migrations.AddField(
            model_name='counselorintake',
            name='father_job',
            field=models.CharField(blank=True, max_length=120, verbose_name='مهنة الأب'),
        ),
        migrations.AddField(
            model_name='counselorintake',
            name='father_served_southern',
            field=models.BooleanField(blank=True, null=True, verbose_name='هل أُصيب الأب في الحد الجنوبي؟'),
        ),
        migrations.AddField(
            model_name='counselorintake',
            name='gets_everything_easily',
            field=models.BooleanField(blank=True, null=True, verbose_name='هل تحصل على كل ما تريد بسهولة؟'),
        ),
        migrations.AddField(
            model_name='counselorintake',
            name='house_ownership',
            field=models.CharField(blank=True, choices=[('own', 'ملك'), ('rent', 'إيجار'), ('grant', 'هبة'), ('waqf', 'وقف'), ('other', 'أخرى')], max_length=10, verbose_name='ملكية السكن'),
        ),
        migrations.AddField(
            model_name='counselorintake',
            name='house_type',
            field=models.CharField(blank=True, choices=[('apartment', 'شقة'), ('villa', 'فيلا'), ('floor', 'دور'), ('traditional', 'بيت شعبي'), ('other', 'نوع آخر')], max_length=20, verbose_name='نوع السكن'),
        ),
        migrations.AddField(
            model_name='counselorintake',
            name='house_type_other',
            field=models.CharField(blank=True, max_length=120, verbose_name='نوع سكن (أخرى)'),
        ),
        migrations.AddField(
            model_name='counselorintake',
            name='mother_alive',
            field=models.BooleanField(blank=True, null=True, verbose_name='هل الأم على قيد الحياة؟'),
        ),
        migrations.AddField(
            model_name='counselorintake',
            name='mother_education',
            field=models.CharField(blank=True, choices=[('illiteracy', 'يقرأ ويكتب'), ('primary', 'الابتدائية'), ('middle', 'المتوسطة'), ('high', 'الثانوية'), ('bachelor', 'بكالوريوس'), ('master', 'ماجستير'), ('phd', 'دكتوراه')], max_length=20, verbose_name='المستوى التعليمي للأم'),
        ),
        migrations.AddField(
            model_name='counselorintake',
            name='mother_job',
            field=models.CharField(blank=True, max_length=120, verbose_name='مهنة الأم'),
        ),
        migrations.AddField(
            model_name='counselorintake',
            name='parents_status',
            field=models.CharField(blank=True, choices=[('stable', 'مستقران'), ('separated', 'منفصلان')], max_length=12, verbose_name='الحالة الاجتماعية للوالدين'),
        ),
        migrations.AddField(
            model_name='counselorintake',
            name='receives_social_support',
            field=models.BooleanField(blank=True, null=True, verbose_name='هل يتم صرف ضمان اجتماعي لكم؟'),
        ),
        migrations.AddField(
            model_name='counselorintake',
            name='siblings_count',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='عدد الإخوة والأخوات'),
        ),
        migrations.AlterField(
            model_name='counselorintake',
            name='student_behavior',
            field=models.TextField(blank=True, verbose_name='وصف السلوك/المشكلة'),
        ),
    ]
