# Generated by Django 5.2.5 on 2025-08-17 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referrals', '0008_counselorintake_birth_order_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsTicker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=300, verbose_name='نص الشريط')),
                ('is_active', models.BooleanField(default=True, verbose_name='مفعل')),
                ('starts_at', models.DateTimeField(blank=True, null=True, verbose_name='يبدأ من')),
                ('ends_at', models.DateTimeField(blank=True, null=True, verbose_name='ينتهي في')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'شريط إخباري',
                'verbose_name_plural': 'أشرطة إخبارية',
                'ordering': ['-created_at'],
            },
        ),
    ]
