# Generated by Django 5.2.5 on 2025-08-25 04:28

import django.db.models.deletion
import referrals.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referrals', '0009_newsticker'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='action',
            options={'ordering': ['created_at'], 'verbose_name': 'إجراء', 'verbose_name_plural': 'إجراءات'},
        ),
        migrations.AlterModelOptions(
            name='actionattachment',
            options={'ordering': ['-uploaded_at'], 'verbose_name': 'مرفق إجراء', 'verbose_name_plural': 'مرفقات الإجراءات'},
        ),
        migrations.AlterModelOptions(
            name='attachment',
            options={'ordering': ['-uploaded_at'], 'verbose_name': 'مرفق إحالة', 'verbose_name_plural': 'مرفقات الإحالات'},
        ),
        migrations.AlterModelOptions(
            name='referral',
            options={'ordering': ['-created_at'], 'verbose_name': 'إحالة', 'verbose_name_plural': 'إحالات'},
        ),
        migrations.AddField(
            model_name='referral',
            name='has_reply',
            field=models.BooleanField(db_index=True, default=False, verbose_name='يوجد رد'),
        ),
        migrations.AddField(
            model_name='referral',
            name='is_opened_by_assignee',
            field=models.BooleanField(db_index=True, default=False, verbose_name='فُتحت من المكلّف'),
        ),
        migrations.AlterField(
            model_name='action',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='الكاتب'),
        ),
        migrations.AlterField(
            model_name='action',
            name='content',
            field=models.TextField(blank=True, verbose_name='المحتوى'),
        ),
        migrations.AlterField(
            model_name='action',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='أُنشئ في'),
        ),
        migrations.AlterField(
            model_name='action',
            name='kind',
            field=models.CharField(choices=[('REPLY', 'رد'), ('NOTE', 'ملاحظة'), ('DECISION', 'قرار')], default='REPLY', max_length=12, verbose_name='النوع'),
        ),
        migrations.AlterField(
            model_name='action',
            name='referral',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='referrals.referral', verbose_name='الإحالة'),
        ),
        migrations.AlterField(
            model_name='actionattachment',
            name='action',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='referrals.action', verbose_name='الإجراء'),
        ),
        migrations.AlterField(
            model_name='actionattachment',
            name='file',
            field=models.FileField(upload_to=referrals.models.action_upload_path, verbose_name='الملف'),
        ),
        migrations.AlterField(
            model_name='actionattachment',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الرفع'),
        ),
        migrations.AlterField(
            model_name='actionattachment',
            name='uploaded_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='تم الرفع بواسطة'),
        ),
        migrations.AlterField(
            model_name='attachment',
            name='file',
            field=models.FileField(upload_to=referrals.models.referral_upload_path, verbose_name='الملف'),
        ),
        migrations.AlterField(
            model_name='attachment',
            name='referral',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='referrals.referral', verbose_name='الإحالة'),
        ),
        migrations.AlterField(
            model_name='attachment',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الرفع'),
        ),
        migrations.AlterField(
            model_name='attachment',
            name='uploaded_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='تم الرفع بواسطة'),
        ),
        migrations.AlterField(
            model_name='newsticker',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='أُنشئ في'),
        ),
        migrations.AlterField(
            model_name='referral',
            name='assignee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_referrals', to=settings.AUTH_USER_MODEL, verbose_name='المكلّف'),
        ),
        migrations.AlterField(
            model_name='referral',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='أُنشئت في'),
        ),
        migrations.AlterField(
            model_name='referral',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_referrals', to=settings.AUTH_USER_MODEL, verbose_name='أنشأها'),
        ),
        migrations.AlterField(
            model_name='referral',
            name='details',
            field=models.TextField(verbose_name='التفاصيل'),
        ),
        migrations.AlterField(
            model_name='referral',
            name='grade',
            field=models.CharField(choices=[('1', 'الصف 1'), ('2', 'الصف 2'), ('3', 'الصف 3'), ('4', 'الصف 4'), ('5', 'الصف 5'), ('6', 'الصف 6'), ('7', 'الصف 7'), ('8', 'الصف 8'), ('9', 'الصف 9'), ('10', 'الصف 10'), ('11', 'الصف 11'), ('12', 'الصف 12')], max_length=2, verbose_name='الصف'),
        ),
        migrations.AlterField(
            model_name='referral',
            name='reference',
            field=models.CharField(default=referrals.models.generate_reference, editable=False, max_length=20, unique=True, verbose_name='المرجع'),
        ),
        migrations.AlterField(
            model_name='referral',
            name='referral_type',
            field=models.CharField(choices=[('behavior', 'سلوكي'), ('academic', 'تحصيلي'), ('health', 'صحي'), ('other', 'أخرى')], max_length=20, verbose_name='نوع الإحالة'),
        ),
        migrations.AlterField(
            model_name='referral',
            name='status',
            field=models.CharField(choices=[('NEW', 'جديدة'), ('UNDER_REVIEW', 'قيد المراجعة'), ('SENT_TO_DEPUTY', 'محالة لوكيل'), ('CLOSED', 'مغلقة')], default='NEW', max_length=20, verbose_name='الحالة'),
        ),
        migrations.AlterField(
            model_name='referral',
            name='student_name',
            field=models.CharField(max_length=120, verbose_name='اسم الطالب'),
        ),
        migrations.AlterField(
            model_name='referral',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='آخر تحديث'),
        ),
    ]
