# Generated by Django 5.2.5 on 2025-08-12 19:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150, verbose_name='الاسم الثلاثي')),
                ('role', models.CharField(choices=[('وكيل الشؤون المدرسية', 'وكيل الشؤون المدرسية'), ('وكيل الشؤون التعليمية', 'وكيل الشؤون التعليمية'), ('وكيل شؤون الطلاب', 'وكيل شؤون الطلاب'), ('موجه طلابي', 'موجه طلابي'), ('إداري', 'إداري'), ('مدير المدرسة', 'مدير المدرسة'), ('معلم', 'معلم')], max_length=50, verbose_name='الدور')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
