"""
Django settings for kingabdulaziz205 project.

Generated by 'django-admin startproject' using Django 5.2.4.
"""

from pathlib import Path

# المسارات الأساسية
BASE_DIR = Path(__file__).resolve().parent.parent

# إعدادات أساسية
SECRET_KEY = 'django-insecure--yj&bf*x+ck1mr&39&jh29=p*qz(g*bf11!wab8ectrmk54&og'
DEBUG = True
ALLOWED_HOSTS = ["127.0.0.1", "localhost"]

# تعريف التطبيقات
INSTALLED_APPS = [
    # Django apps
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # Local apps
    'accounts',
    'referrals',
    'workflow',
    'messaging',  # ⭐ تطبيق المراسلات
]

# الوسطاء
MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.locale.LocaleMiddleware',  # دعم العربية وتعدد اللغات
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'kingabdulaziz205.urls'

# القوالب
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        # تعريف مجلد القوالب: C:\Users\Test2\kingabdulaziz205\templates
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.i18n',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'referrals.context_processors.active_news_ticker',  # ✅ تمرير الشريط الإخباري لكل القوالب
            ],
        },
    },
]

WSGI_APPLICATION = 'kingabdulaziz205.wsgi.application'

# قاعدة البيانات (SQLite للتطوير)
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

# تحقق كلمات المرور
AUTH_PASSWORD_VALIDATORS = [
    {'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator'},
    {'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator'},
    {'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator'},
    {'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator'},
]

# التدويل واللغة والتوقيت
LANGUAGE_CODE = 'ar'
TIME_ZONE = 'Asia/Riyadh'
USE_I18N = True
USE_TZ = True

LANGUAGES = [
    ('ar', 'Arabic'),
    ('en', 'English'),
]

LOCALE_PATHS = [BASE_DIR / 'locale']

# ---------------------------------
# الملفات الثابتة (Static)
# ---------------------------------
STATIC_URL = '/static/'
STATICFILES_DIRS = [
    BASE_DIR / 'static',
]
STATIC_ROOT = BASE_DIR / 'static_collected'

# ---------------------------------
# رفع الملفات (Media)
# ---------------------------------
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# ---------------------------------
# توجيه ما بعد الدخول/الخروج
# ---------------------------------
LOGIN_REDIRECT_URL = '/referrals/'   # بعد تسجيل الدخول
LOGOUT_REDIRECT_URL = '/'            # بعد تسجيل الخروج
LOGIN_URL = '/accounts/login/'       # مسار صفحة الدخول

# نوع المفتاح الافتراضي
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# كود المدرسة السري للتسجيل
SCHOOL_SECRET_CODE = '61122_2025'
