"""
Django settings for kingabdulaziz205 project.

Generated by 'django-admin startproject' using Django 5.2.4.
"""

from pathlib import Path
import os
from dotenv import load_dotenv

# =========================
# تحميل متغيرات البيئة
# =========================
BASE_DIR = Path(__file__).resolve().parent.parent
load_dotenv(BASE_DIR / ".env")

# =========================
# إعدادات أساسية
# =========================
SECRET_KEY = os.getenv(
    "DJANGO_SECRET_KEY",
    "django-insecure--yj&bf*x+ck1mr&39&jh29=p*qz(g*bf11!wab8ectrmk54&og",
)
DEBUG = os.getenv("DJANGO_DEBUG", "1") == "1"
ALLOWED_HOSTS = ["127.0.0.1", "localhost", ".onrender.com"]

# =========================
# تعريف التطبيقات
# =========================
INSTALLED_APPS = [
    # Django apps
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",

    # Cloudinary (للميديا)
    "cloudinary",
    "cloudinary_storage",

    # Local apps
    "accounts",
    "referrals",
    "workflow",
    "messaging",  # ⭐ تطبيق المراسلات
]

# =========================
# الوسطاء
# =========================
MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.locale.LocaleMiddleware",  # دعم العربية وتعدد اللغات
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "kingabdulaziz205.urls"

# =========================
# القوالب
# =========================
TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.i18n",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                "referrals.context_processors.active_news_ticker",  # ✅ تمرير الشريط الإخباري
            ],
        },
    },
]

WSGI_APPLICATION = "kingabdulaziz205.wsgi.application"

# =========================
# قاعدة البيانات
# =========================
if os.getenv("USE_POSTGRES", "0") == "1":
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.postgresql",
            "HOST": os.getenv("DB_HOST"),
            "PORT": os.getenv("DB_PORT"),
            "NAME": os.getenv("DB_NAME"),
            "USER": os.getenv("DB_USER"),
            "PASSWORD": os.getenv("DB_PASSWORD"),
        }
    }
else:
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.sqlite3",
            "NAME": BASE_DIR / "db.sqlite3",
        }
    }

# =========================
# تحقق كلمات المرور
# =========================
AUTH_PASSWORD_VALIDATORS = [
    {"NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator"},
    {"NAME": "django.contrib.auth.password_validation.MinimumLengthValidator"},
    {"NAME": "django.contrib.auth.password_validation.CommonPasswordValidator"},
    {"NAME": "django.contrib.auth.password_validation.NumericPasswordValidator"},
]

# =========================
# التدويل واللغة والتوقيت
# =========================
LANGUAGE_CODE = "ar"
TIME_ZONE = "Asia/Riyadh"
USE_I18N = True
USE_TZ = True

LANGUAGES = [
    ("ar", "Arabic"),
    ("en", "English"),
]

LOCALE_PATHS = [BASE_DIR / "locale"]

# =========================
# الملفات الثابتة (Static)
# =========================
STATIC_URL = "/static/"
STATICFILES_DIRS = [BASE_DIR / "static"]
STATIC_ROOT = BASE_DIR / "static_collected"

# =========================
# رفع الملفات (Media) عبر Cloudinary
# =========================
MEDIA_URL = "/media/"           # يبقى كما هو (غير مستخدم مع التخزين السحابي)
MEDIA_ROOT = BASE_DIR / "media" # يُستخدم محليًا فقط إذا عطّلت Cloudinary

# Cloudinary config (بيانات من .env)
import cloudinary
cloudinary.config(
    cloud_name=os.getenv("CLOUDINARY_CLOUD_NAME"),
    api_key=os.getenv("CLOUDINARY_API_KEY"),
    api_secret=os.getenv("CLOUDINARY_API_SECRET"),
    secure=True,
)

# تخزين الميديا على Cloudinary
DEFAULT_FILE_STORAGE = "cloudinary_storage.storage.MediaCloudinaryStorage"

# =========================
# توجيه ما بعد الدخول/الخروج
# =========================
LOGIN_REDIRECT_URL = "/referrals/"
LOGOUT_REDIRECT_URL = "/"
LOGIN_URL = "/accounts/login/"

# =========================
# نوع المفتاح الافتراضي
# =========================
DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# =========================
# إعدادات خاصة بالمشروع
# =========================
SCHOOL_SECRET_CODE = "61122_2025"
